# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='wood_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tartak.Wood_kind'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='wood_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='tartak.Wood_kind'),
        ),
    ]
