# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0002_auto_20160704_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tartak.Driver'),
            preserve_default=False,
        ),
    ]
