# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0003_order_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='price',
            new_name='detail_price',
        ),
        migrations.RenameField(
            model_name='wood_kind',
            old_name='price',
            new_name='detail_price',
        ),
        migrations.AddField(
            model_name='order',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]