# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0004_auto_20160704_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_shipped',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='forest_district',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='wood_kind',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
