# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0005_auto_20160705_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='wood_kind',
            name='forest_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wood_kinds', to='tartak.Forest_district'),
            preserve_default=False,
        ),
    ]