# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0007_auto_20160705_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='order_item',
            unique_together=set([('id', 'wood_kind')]),
        ),
    ]
