# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0009_auto_20160705_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order_item',
            unique_together=set([('order', 'wood_kind')]),
        ),
    ]