# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0010_auto_20160705_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='is_using_regular_price',
        ),
    ]