# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 09:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0011_remove_order_item_is_using_regular_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Imi\u0119'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='WZ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tartak.Driver', verbose_name='Kierowca'),
        ),
        migrations.AlterField(
            model_name='order',
            name='forest_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tartak.Forest_district', verbose_name='Nadle\u015bnictwo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pieces',
            field=models.IntegerField(default=0, verbose_name='Liczba sztuk'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Masa'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='detail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cena detaliczna'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tartak.Order', verbose_name='Zam\xf3wienie'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='wood_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tartak.Wood_kind', verbose_name='Rodzaj drewna'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Masa'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='tartak.Contractor', verbose_name='Kontrahent'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='tartak.Order', verbose_name='Zam\xf3wienie'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='wood_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='tartak.Wood_kind', verbose_name='Rodzaj drewna'),
        ),
        migrations.AlterField(
            model_name='wood_kind',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='wood_kind',
            name='detail_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='wood_kind',
            name='forest_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wood_kinds', to='tartak.Forest_district', verbose_name='Nadle\u015bnictwo'),
        ),
    ]
