# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 17:15
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0013_auto_20160707_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pieces',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Liczba sztuk'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Masa'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='detail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cena detaliczna'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Masa'),
        ),
        migrations.AlterField(
            model_name='wood_kind',
            name='detail_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cena'),
        ),
    ]