# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0014_auto_20160707_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forest_district',
            name='contract',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='forest_district',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='WZ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tartak.Driver', verbose_name='Kierowca'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='contractor',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='tartak.Contractor', verbose_name='Kontrahent'),
        ),
        migrations.AlterField(
            model_name='wood_kind',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='wood_kind',
            name='forest_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wood_kinds', to='tartak.Forest_district', verbose_name='Nadle\u015bnictwo'),
        ),
    ]
