# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 07:20
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0014_auto_20160707_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Masa')),
                ('date', models.DateField(verbose_name='Data')),
                ('wood_type', models.CharField(default='Brak manipulacji', max_length=100, verbose_name='Rodzaj drewna (po manipulacji)')),
            ],
            options={
                'verbose_name': 'Dostawa ko\u0144cowa',
                'verbose_name_plural': 'Dostawy ko\u0144cowe',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Kwit wywozowy', 'verbose_name_plural': 'Kwity wywozowe'},
        ),
        migrations.AlterModelOptions(
            name='order_item',
            options={'verbose_name': 'Pozycja dostawy', 'verbose_name_plural': 'Pozycje dostawy'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': 'Dostawa po\u015brednia', 'verbose_name_plural': 'Dostawy po\u015brednie'},
        ),
        migrations.AlterModelOptions(
            name='wood_kind',
            options={'verbose_name': 'Sortyment', 'verbose_name_plural': 'Sortymenty'},
        ),
        migrations.AlterField(
            model_name='contractor',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='forest_district',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='WZ'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tartak.Order', verbose_name='Kwit wywozowy'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='wood_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tartak.Wood_kind', verbose_name='Sortyment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='tartak.Order', verbose_name='Kwit wywozowy'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='wood_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='tartak.Wood_kind', verbose_name='Sortyment'),
        ),
        migrations.AlterField(
            model_name='wood_kind',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Kod'),
        ),
        migrations.AddField(
            model_name='final_shipment',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_shipments', to='tartak.Contractor', verbose_name='Kontrahent'),
        ),
        migrations.AddField(
            model_name='final_shipment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_shipments', to='tartak.Driver', verbose_name='Kierowca'),
        ),
        migrations.AddField(
            model_name='final_shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_shipments', to='tartak.Order', verbose_name='Kwit wywozowy'),
        ),
        migrations.AddField(
            model_name='final_shipment',
            name='wood_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_shipments', to='tartak.Wood_kind', verbose_name='Sortyment'),
        ),
    ]
