# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0015_auto_20160718_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_shipment',
            name='wood_kind',
        ),
    ]
