# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 01:32
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0016_auto_20160726_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor_shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Masa')),
                ('date', models.DateField(verbose_name='Data')),
                ('wood_type', models.CharField(default='Brak manipulacji', max_length=100, verbose_name='Rodzaj drewna (po manipulacji)')),
            ],
            options={
                'verbose_name': 'Dostawa ko\u0144cowa ze sk\u0142adnicy',
                'verbose_name_plural': 'Dostawy ko\u0144cowe ze sk\u0142adnicy',
            },
        ),
        migrations.AddField(
            model_name='contractor',
            name='is_depot',
            field=models.BooleanField(default=False, verbose_name='Sk\u0142adnica'),
        ),
        migrations.AddField(
            model_name='contractor_shipment',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_shipments_to', to='tartak.Contractor', verbose_name='Kontrahent'),
        ),
        migrations.AddField(
            model_name='contractor_shipment',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_shipments_from', to='tartak.Contractor', verbose_name='Sk\u0142adnica'),
        ),
        migrations.AddField(
            model_name='contractor_shipment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_shipments', to='tartak.Driver', verbose_name='Kierowca'),
        ),
    ]
