# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 03:53
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0017_auto_20160728_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('date_from', models.DateField(verbose_name='Obowi\u0105zuje od')),
                ('date_to', models.DateField(verbose_name='Obowi\u0105zuje do')),
            ],
            options={
                'verbose_name': 'Umowa',
                'verbose_name_plural': 'Umowy',
            },
        ),
        migrations.CreateModel(
            name='Deal_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod sortymentu')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Masa')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_items', to='tartak.Deal', verbose_name='Umowa')),
            ],
            options={
                'verbose_name': 'Pozycja umowy',
                'verbose_name_plural': 'Pozycje umowy',
            },
        ),
        migrations.AlterField(
            model_name='forest_district',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='forest_district',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AddField(
            model_name='deal',
            name='forest_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='tartak.Forest_district', verbose_name='Nadle\u015bnictwo'),
        ),
    ]
