# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tartak', '0018_auto_20160728_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal_item',
            name='code',
            field=models.CharField(help_text='np. W_STANDARD_SW', max_length=30, verbose_name='Kod sortymentu'),
        ),
    ]
